@baseApi = http://localhost:8080/api

### admin Login
# @name adminLogin
POST {{baseApi}}/login
Content-Type: application/json

{
    "username": "admin",
    "password": "123"
}

### dev login
# @name devLogin
POST {{baseApi}}/login
Content-Type: application/json

{
    "username": "dev",
    "password": "123"
}


### create admin
# @name create-admin
@token = {{adminLogin.response.body.*}}
POST http://localhost:8080/api/admin/user
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "username":"admin99",
    "firstName":"admin1",
    "lastName": "nimda",
    "userType":"admin",
    "email":"mic4126@gmail.com"
}

### create dev
POST http://localhost:8080/admin/user
Content-Type: application/json

{
    "username":"dev1",
    "firstName":"admin1",
    "lastName": "nimda",
    "userType":"dev",
    "email":"mic4126@gmail.com"
}

### reset password

POST http://localhost:8080/api/admin/user/password/admin
Content-Type: application/json

{
    "username":"admin",
    "email":"mic4126@gmail.com"
}

### change password

PUT http://localhost:8080/admin/user/password/admin
Content-Type: application/json

{
    "username":"dev",
    "password":"123",
    "newPassword":"123"
}

### change user info

PUT http://localhost:8080/admin/user/admin
Content-Type: application/json

{
    "username":"admin",
    "email":"mic4126@gmail.com",
    "firstName":"nimda",
    "lastName":"admin",
    "password":"123"
    
}


### Delete User

DELETE http://localhost:8080/admin/user/admin

### Add Project
POST http://localhost:8080/api/project
Content-Type: application/json

{
    "projectName":"test5",
    "developers":["dev","dev1"]
}



### Put Desc (ENG)
PUT http://localhost:8080/api/project/desc
Content-Type: application/x-www-form-urlencoded

projectId=15
&desc=Lorem_ipsum
&lang=ENG

### Get Desc (ENG)
GET  http://localhost:8080/api/project/desc
?projectId=15
&lang=ENG

### Get Project Name
GET http://localhost:8080/api/project/name
?projectId=15
&lang=ENG

### Get Contact

GET http://localhost:8080/api/project/contact
?projectId=15

### Get Tag
GET http://localhost:8080/api/project/15/tag


### Login
POST  http://localhost:8080/api/login
Content-Type: application/json

{
    "username":"admin",
    "password":"123"
}

### Get Dev usres
GET http://localhost:8080/api/admin/user
?userType=dev

### Get Admin usres
GET http://localhost:8080/api/admin/user
?userType=admin

### add dev to project 
POST http://localhost:8080/api/project/15/user
Content-Type: application/x-www-form-urlencoded

username=dev6

### delete dev from project

DELETE  http://localhost:8080/api/project/15/user/dev6


### Get All Project
GET http://localhost:8080/api/project


### Get Dev's project

GET http://localhost:8080/api/admin/user/dev/project

### Get Details

GET  http://localhost:8080/api/project/15/detail

### Get Attachment List
GET  http://localhost:8080/api/project/15/attachment


### Get Detail Attachment list
GET  http://localhost:8080/api/project/detail/1/attachment

### Put Detail
PUT {{baseApi}}/project/15/detail/1
Content-Type: application/json

{
  "detailId": 1,
  "projectId": 15,
  "detailName": "Test Detail",
  "detailName_TC": "測試",
  "detailName_SC": "測試",
  "detailDesc": "Test",
  "detailDesc_TC": "測試測試測試測試",
  "detailDesc_SC": "測試"
}

### get dev's project list
@token = {{devLogin.response.body.*}}

GET http://localhost:4200/api/admin/user/dev/project
Authorization: Bearer {{token}}