### create admin
POST http://localhost:8080/admin/user
Content-Type: application/json

{
    "username":"admin3",
    "firstName":"admin1",
    "lastName": "nimda",
    "userType":"admin",
    "email":"mic4126@gmail.com"
}

### create dev
POST http://localhost:8080/admin/user
Content-Type: application/json

{
    "username":"dev1",
    "firstName":"admin1",
    "lastName": "nimda",
    "userType":"dev",
    "email":"mic4126@gmail.com"
}

### reset password

POST http://localhost:8080/api/admin/user/password/admin
Content-Type: application/json

{
    "username":"admin",
    "email":"mic4126@gmail.com"
}

### change password

PUT http://localhost:8080/admin/user/password/admin
Content-Type: application/json

{
    "username":"dev",
    "password":"123",
    "newPassword":"123"
}

### change user info

PUT http://localhost:8080/admin/user/admin
Content-Type: application/json

{
    "username":"admin",
    "email":"mic4126@gmail.com",
    "firstName":"nimda",
    "lastName":"admin",
    "password":"123"
    
}


### Delete User

DELETE http://localhost:8080/admin/user/admin

### Add Project
POST http://localhost:8080/api/project
Content-Type: application/json

{
    "projectName":"test5",
    "developers":["dev","dev1"]
}



### Put Desc (ENG)
PUT http://localhost:8080/api/project/desc
Content-Type: application/x-www-form-urlencoded

projectId=15
&desc=Lorem_ipsum
&lang=ENG

### Get Desc (ENG)
GET  http://localhost:8080/api/project/desc
?projectId=15
&lang=ENG

### Get Project Name
GET http://localhost:8080/api/project/name
?projectId=15
&lang=ENG

### Get Contact

GET http://localhost:8080/api/project/contact
?projectId=15

### Get Tag
GET http://localhost:8080/api/project/15/tag


### Login
POST  http://localhost:8080/api/login
Content-Type: application/json

{
    "username":"admin",
    "password":"123"
}

### Get Dev usres
GET http://localhost:8080/api/admin/user
?userType=dev

### Get Admin usres
GET http://localhost:8080/api/admin/user
?userType=admin

### add dev to project 
POST http://localhost:8080/api/project/15/user
Content-Type: application/x-www-form-urlencoded

username=dev6

### delete dev from project

DELETE  http://localhost:8080/api/project/15/user/dev6


### Get All Project
GET http://localhost:8080/api/project


### Get Dev's project

GET http://localhost:8080/api/admin/user/dev/project